// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8-BI128vEK9a3q2Kemjv-ElrMFtIO2pE',
    appId: '1:660612640173:web:3ed89038bed33c9f104524',
    messagingSenderId: '660612640173',
    projectId: 'promptia-332d0',
    authDomain: 'promptia-332d0.firebaseapp.com',
    storageBucket: 'promptia-332d0.firebasestorage.app',
    measurementId: 'G-6SQ02BPCNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcKgeeoJ724TraG5Kbp2CI5k9ReYIRhaM',
    appId: '1:660612640173:android:a0fb2fda8e0c6e59104524',
    messagingSenderId: '660612640173',
    projectId: 'promptia-332d0',
    storageBucket: 'promptia-332d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRlz-rUGt0VFoomPa3llWda4ZSGIZ4Esg',
    appId: '1:660612640173:ios:1373a7402df79cc4104524',
    messagingSenderId: '660612640173',
    projectId: 'promptia-332d0',
    storageBucket: 'promptia-332d0.firebasestorage.app',
    iosBundleId: 'com.example.supabaseTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRlz-rUGt0VFoomPa3llWda4ZSGIZ4Esg',
    appId: '1:660612640173:ios:1373a7402df79cc4104524',
    messagingSenderId: '660612640173',
    projectId: 'promptia-332d0',
    storageBucket: 'promptia-332d0.firebasestorage.app',
    iosBundleId: 'com.example.supabaseTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8-BI128vEK9a3q2Kemjv-ElrMFtIO2pE',
    appId: '1:660612640173:web:8fa61764aa2fa070104524',
    messagingSenderId: '660612640173',
    projectId: 'promptia-332d0',
    authDomain: 'promptia-332d0.firebaseapp.com',
    storageBucket: 'promptia-332d0.firebasestorage.app',
    measurementId: 'G-WSBL0VFHEF',
  );
}
